APPLICATION := hello-world
BOARD := business-card
RIOTBASE ?= $(CURDIR)/../../RIOT

EXTERNAL_BOARD_DIRS := $(CURDIR)/../../boards
EXTERNAL_MODULE_DIRS := $(CURDIR)/../../modules

DEVELHELP ?= 1
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
